### ISSUE TITLE
Depth instead of Pressure levels

### ISSUE THREAD

**Issue by EPauthenet** [euroargodev/OSnet#1]
Salut Matthieu,
on voudrait corriger l’imprécision que j’ai faite en laissant les niveaux verticaux en pression et pas en profondeur. Donc il faudrait transformer les niveaux de pression dans les fichiers CORA avant l’interpolation vertical. Pour ça tu peux utiliser la fonction z_from_p du module gsw. Et ensuite assigner la profondeur comme nouvelle variable (juste avant la ligne `for n in range(0,N):`):

```
z = -gsw.z_from_p(ds.PRES, ds.LAT)
ds = ds.assign(variables={"DEPTH": (('N_PROF','N_PRES'), z.data)})
```

Ensuite il faut simplement remplacer tout les PRES_INTERPOLATED par DEPTH comme dimension dans tout le code. Un peu fastidieux mais comme ça c’est réglé dès le début et on a pas à traduire de pression à profondeur.
Et puis évidemment faire l’interpolation sur ds.DEPTH au lieu de ds.PRES.

**Comment by LJMatthieu** [comment]
OK
